export const Types = {
  LOGIN: 'LOGIN',
  ADD_USER: 'ADD_USER',
  FORM_SUBMITION_STATUS: 'FORM_SUBMITION_STATUS',

  NAVIGATE_PATH: 'NAVIGATE_PATH',
  
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  FETCH_ALL_MEMORIES: 'FETCH_ALL_MEMORIES',
  CREATE_MEMORY: 'CREATE_MEMORY',
  UPDATE_MEMORY: 'UPDATE_MEMORY',
  DELETE_MEMORY: 'DELETE_MEMORY'
  };